services:
  inventory:
    build: .
    ports:
      - "8082:8082"
    env_file: .env
    volumes:
      - /var/log:/app/logs
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - inventory_network

  db:
    image: postgres:15-alpine
    volumes:
      - inventory_data:/var/lib/postgresql/data
      - ./db/initDB:/docker-entrypoint-initdb.d
    env_file: .env
    ports:
        - "5432:5432"
    restart: always
    networks:
      - inventory_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U talgat -d inventory" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
volumes:
  inventory_data:

networks:
  inventory_network: